-- MySQL Script generated by MySQL Workbench
-- Mon Jun 12 20:41:57 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`dieta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dieta` (
  `iddieta` INT NOT NULL,
  `cafe` LONGTEXT NULL,
  `almoco` LONGTEXT NULL,
  `lanche` LONGTEXT NULL,
  `janta` LONGTEXT NULL,
  PRIMARY KEY (`iddieta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pacientes` (
  `idpacientes` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `peso` FLOAT NOT NULL,
  `altura` FLOAT NOT NULL,
  `idade` INT NOT NULL,
  `gordura_corporal` FLOAT NOT NULL,
  `imc` FLOAT NULL,
  `dieta_iddieta` INT NOT NULL,
  PRIMARY KEY (`idpacientes`, `dieta_iddieta`),
  UNIQUE INDEX `idpacientes_UNIQUE` (`idpacientes` ASC),
  INDEX `fk_pacientes_dieta1_idx` (`dieta_iddieta` ASC),
  CONSTRAINT `fk_pacientes_dieta1`
    FOREIGN KEY (`dieta_iddieta`)
    REFERENCES `mydb`.`dieta` (`iddieta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nutricionista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nutricionista` (
  `idnutricionista` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `idade` INT NOT NULL,
  `valor_consulta` INT NOT NULL,
  `pacientes_idpacientes` INT NOT NULL,
  `dieta_iddieta` INT NOT NULL,
  PRIMARY KEY (`idnutricionista`, `pacientes_idpacientes`, `dieta_iddieta`),
  INDEX `fk_nutricionista_pacientes_idx` (`pacientes_idpacientes` ASC),
  INDEX `fk_nutricionista_dieta1_idx` (`dieta_iddieta` ASC),
  CONSTRAINT `fk_nutricionista_pacientes`
    FOREIGN KEY (`pacientes_idpacientes`)
    REFERENCES `mydb`.`pacientes` (`idpacientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nutricionista_dieta1`
    FOREIGN KEY (`dieta_iddieta`)
    REFERENCES `mydb`.`dieta` (`iddieta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO dieta (iddieta, cafe, almoco, lanche, janta) VALUES ("1", "cafe", "almoco", "lanche", "janta");
INSERT INTO pacientes (idpacientes, nome, peso, altura, idade, gordura_corporal, imc, dieta_iddieta) VALUES ("01", "Lucas", "90", "175", "21", "25", "26", "1");
INSERT INTO pacientes (idpacientes, nome, peso, altura, idade, gordura_corporal, imc, dieta_iddieta) VALUES ("02", "Matheus", "80", "172", "22", "30", "27", "1");
INSERT INTO pacientes (idpacientes, nome, peso, altura, idade, gordura_corporal, imc, dieta_iddieta) VALUES ("03", "Joao", "88", "182", "19", "18", "23", "1");
INSERT INTO pacientes (idpacientes, nome, peso, altura, idade, gordura_corporal, imc, dieta_iddieta) VALUES ("04", "Leo", "74", "177", "23", "15", "22", "1");
INSERT INTO nutricionista (idnutricionista, nome, idade, valor_consulta, pacientes_idpacientes, dieta_iddieta) VALUES ("01", "Lais", "23", "100", "01", "1");

SELECT * FROM pacientes WHERE idpacientes = "01";
SELECT idpacientes, nome, altura FROM pacientes WHERE idade >=18 AND idade <=21;
SELECT * FROM pacientes WHERE nome like "%Leo%";
SELECT * FROM pacientes ORDER BY peso ASC;
SELECT nome, peso FROM pacientes WHERE altura = "177" ORDER BY peso DESC;
SELECT MAX(peso) as Maior_Peso FROM pacientes;
SELECT MAX(imc) as Maior_Imc, MIN(imc) as Menor_Imc FROM pacientes WHERE imc >= 0 and imc <=50;
SELECT AVG(idade) as Media_Idade FROM pacientes;
SELECT COUNT(*) as Total FROM pacientes;
SELECT SUM(peso) as Total_Peso, SUM(altura) as Total_Altura FROM pacientes;
SELECT nome, gordura_corporal FROM pacientes GROUP BY gordura_corporal;
SELECT nome, COUNT(valor_consulta) as Quantidade_Consultas FROM nutricionista GROUP BY valor_consulta;
SELECT nome, SUM(valor_consulta) as Total_Consultas FROM nutricionista GROUP BY nome HAVING SUM(valor_consulta) > 100;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
